//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System;
// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.8.3928.0.
// 

namespace Gsd2Aml.Lib.Models.CAEX3
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.dke.de/CAEX")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.dke.de/CAEX", IsNullable = false)]
    public partial class CAEXFile : CAEXBasicObject
    {

        private string[] superiorStandardVersionField;

        private SourceDocumentInformationType[] sourceDocumentInformationField;

        private CAEXFileExternalReference[] externalReferenceField;

        private CAEXFileInstanceHierarchy[] instanceHierarchyField;

        private CAEXFileInterfaceClassLib[] interfaceClassLibField;

        private CAEXFileRoleClassLib[] roleClassLibField;

        private CAEXFileSystemUnitClassLib[] systemUnitClassLibField;

        private CAEXFileAttributeTypeLib[] attributeTypeLibField;

        private string schemaVersionField;

        private string fileNameField;

        public CAEXFile()
        {
            this.schemaVersionField = "3.0";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SuperiorStandardVersion")]
        public string[] SuperiorStandardVersion
        {
            get
            {
                return this.superiorStandardVersionField;
            }
            set
            {
                this.superiorStandardVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SourceDocumentInformation")]
        public SourceDocumentInformationType[] SourceDocumentInformation
        {
            get
            {
                return this.sourceDocumentInformationField;
            }
            set
            {
                this.sourceDocumentInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExternalReference")]
        public CAEXFileExternalReference[] ExternalReference
        {
            get
            {
                return this.externalReferenceField;
            }
            set
            {
                this.externalReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InstanceHierarchy")]
        public CAEXFileInstanceHierarchy[] InstanceHierarchy
        {
            get
            {
                return this.instanceHierarchyField;
            }
            set
            {
                this.instanceHierarchyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InterfaceClassLib")]
        public CAEXFileInterfaceClassLib[] InterfaceClassLib
        {
            get
            {
                return this.interfaceClassLibField;
            }
            set
            {
                this.interfaceClassLibField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RoleClassLib")]
        public CAEXFileRoleClassLib[] RoleClassLib
        {
            get
            {
                return this.roleClassLibField;
            }
            set
            {
                this.roleClassLibField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SystemUnitClassLib")]
        public CAEXFileSystemUnitClassLib[] SystemUnitClassLib
        {
            get
            {
                return this.systemUnitClassLibField;
            }
            set
            {
                this.systemUnitClassLibField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttributeTypeLib")]
        public CAEXFileAttributeTypeLib[] AttributeTypeLib
        {
            get
            {
                return this.attributeTypeLibField;
            }
            set
            {
                this.attributeTypeLibField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SchemaVersion
        {
            get
            {
                return this.schemaVersionField;
            }
            set
            {
                this.schemaVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.dke.de/CAEX")]
    public partial class SourceDocumentInformationType
    {

        private string originNameField;

        private string originIDField;

        private string originVendorField;

        private string originVendorURLField;

        private string originVersionField;

        private string originReleaseField;

        private System.DateTime lastWritingDateTimeField;

        private string originProjectTitleField;

        private string originProjectIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OriginName
        {
            get
            {
                return this.originNameField;
            }
            set
            {
                this.originNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OriginID
        {
            get
            {
                return this.originIDField;
            }
            set
            {
                this.originIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OriginVendor
        {
            get
            {
                return this.originVendorField;
            }
            set
            {
                this.originVendorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OriginVendorURL
        {
            get
            {
                return this.originVendorURLField;
            }
            set
            {
                this.originVendorURLField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OriginVersion
        {
            get
            {
                return this.originVersionField;
            }
            set
            {
                this.originVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OriginRelease
        {
            get
            {
                return this.originReleaseField;
            }
            set
            {
                this.originReleaseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime LastWritingDateTime
        {
            get
            {
                return this.lastWritingDateTimeField;
            }
            set
            {
                this.lastWritingDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OriginProjectTitle
        {
            get
            {
                return this.originProjectTitleField;
            }
            set
            {
                this.originProjectTitleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OriginProjectID
        {
            get
            {
                return this.originProjectIDField;
            }
            set
            {
                this.originProjectIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CAEXObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RoleClassType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RoleFamilyType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InterfaceClassType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InterfaceFamilyType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttributeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttributeFamilyType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemUnitClassType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemUnitFamilyType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InternalElementType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttributeValueRequirementType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MappingType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.dke.de/CAEX")]
    public partial class CAEXBasicObject
    {

        private CAEXBasicObjectDescription descriptionField;

        private CAEXBasicObjectVersion versionField;

        private CAEXBasicObjectRevision[] revisionField;

        private CAEXBasicObjectCopyright copyrightField;

        private object[] additionalInformationField;

        private CAEXBasicObjectSourceObjectInformation[] sourceObjectInformationField;

        private ChangeMode changeModeField;

        public CAEXBasicObject()
        {
            this.changeModeField = ChangeMode.state;
        }

        /// <remarks/>
        public CAEXBasicObjectDescription Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public CAEXBasicObjectVersion Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Revision")]
        public CAEXBasicObjectRevision[] Revision
        {
            get
            {
                return this.revisionField;
            }
            set
            {
                this.revisionField = value;
            }
        }

        /// <remarks/>
        public CAEXBasicObjectCopyright Copyright
        {
            get
            {
                return this.copyrightField;
            }
            set
            {
                this.copyrightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalInformation")]
        public object[] AdditionalInformation
        {
            get
            {
                return this.additionalInformationField;
            }
            set
            {
                this.additionalInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SourceObjectInformation")]
        public CAEXBasicObjectSourceObjectInformation[] SourceObjectInformation
        {
            get
            {
                return this.sourceObjectInformationField;
            }
            set
            {
                this.sourceObjectInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ChangeMode.state)]
        public ChangeMode ChangeMode
        {
            get
            {
                return this.changeModeField;
            }
            set
            {
                this.changeModeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.dke.de/CAEX")]
    public partial class CAEXBasicObjectDescription
    {

        private ChangeMode changeModeField;

        private string valueField;

        public CAEXBasicObjectDescription()
        {
            this.changeModeField = ChangeMode.state;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ChangeMode.state)]
        public ChangeMode ChangeMode
        {
            get
            {
                return this.changeModeField;
            }
            set
            {
                this.changeModeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.dke.de/CAEX")]
    public enum ChangeMode
    {

        /// <remarks/>
        state,

        /// <remarks/>
        create,

        /// <remarks/>
        delete,

        /// <remarks/>
        change,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.dke.de/CAEX")]
    public partial class CAEXBasicObjectVersion
    {

        private ChangeMode changeModeField;

        private string valueField;

        public CAEXBasicObjectVersion()
        {
            this.changeModeField = ChangeMode.state;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ChangeMode.state)]
        public ChangeMode ChangeMode
        {
            get
            {
                return this.changeModeField;
            }
            set
            {
                this.changeModeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.dke.de/CAEX")]
    public partial class CAEXBasicObjectRevision : CAEXBasicObject
    {

        private System.DateTime revisionDateField;

        private string oldVersionField;

        private string newVersionField;

        private string authorNameField;

        private string commentField;

        /// <remarks/>
        public System.DateTime RevisionDate
        {
            get
            {
                return this.revisionDateField;
            }
            set
            {
                this.revisionDateField = value;
            }
        }

        /// <remarks/>
        public string OldVersion
        {
            get
            {
                return this.oldVersionField;
            }
            set
            {
                this.oldVersionField = value;
            }
        }

        /// <remarks/>
        public string NewVersion
        {
            get
            {
                return this.newVersionField;
            }
            set
            {
                this.newVersionField = value;
            }
        }

        /// <remarks/>
        public string AuthorName
        {
            get
            {
                return this.authorNameField;
            }
            set
            {
                this.authorNameField = value;
            }
        }

        /// <remarks/>
        public string Comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.dke.de/CAEX")]
    public partial class CAEXBasicObjectCopyright
    {

        private ChangeMode changeModeField;

        private string valueField;

        public CAEXBasicObjectCopyright()
        {
            this.changeModeField = ChangeMode.state;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ChangeMode.state)]
        public ChangeMode ChangeMode
        {
            get
            {
                return this.changeModeField;
            }
            set
            {
                this.changeModeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.dke.de/CAEX")]
    public partial class CAEXBasicObjectSourceObjectInformation
    {

        private string originIDField;

        private string sourceObjIDField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OriginID
        {
            get
            {
                return this.originIDField;
            }
            set
            {
                this.originIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SourceObjID
        {
            get
            {
                return this.sourceObjIDField;
            }
            set
            {
                this.sourceObjIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RoleClassType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RoleFamilyType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InterfaceClassType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InterfaceFamilyType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttributeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttributeFamilyType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemUnitClassType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemUnitFamilyType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InternalElementType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.dke.de/CAEX")]
    public partial class CAEXObject : CAEXBasicObject
    {

        private string idField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RoleFamilyType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.dke.de/CAEX")]
    public partial class RoleClassType : CAEXObject
    {

        private AttributeType[] attributeField;

        private RoleClassTypeExternalInterface[] externalInterfaceField;

        private string refBaseClassPathField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attribute")]
        public AttributeType[] Attribute
        {
            get
            {
                return this.attributeField;
            }
            set
            {
                this.attributeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExternalInterface")]
        public RoleClassTypeExternalInterface[] ExternalInterface
        {
            get
            {
                return this.externalInterfaceField;
            }
            set
            {
                this.externalInterfaceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RefBaseClassPath
        {
            get
            {
                return this.refBaseClassPathField;
            }
            set
            {
                this.refBaseClassPathField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttributeFamilyType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.dke.de/CAEX")]
    public partial class AttributeType : CAEXObject
    {

        private string defaultValueField;

        private string valueField;

        private AttributeTypeRefSemantic[] refSemanticField;

        private AttributeValueRequirementType[] constraintField;

        private AttributeType[] attributeField;

        private string unitField;

        private string attributeDataTypeField;

        private string refAttributeTypeField;

        /// <remarks/>
        public string DefaultValue
        {
            get
            {
                return this.defaultValueField;
            }
            set
            {
                this.defaultValueField = value;
            }
        }

        /// <remarks/>
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RefSemantic")]
        public AttributeTypeRefSemantic[] RefSemantic
        {
            get
            {
                return this.refSemanticField;
            }
            set
            {
                this.refSemanticField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Constraint")]
        public AttributeValueRequirementType[] Constraint
        {
            get
            {
                return this.constraintField;
            }
            set
            {
                this.constraintField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attribute")]
        public AttributeType[] Attribute
        {
            get
            {
                return this.attributeField;
            }
            set
            {
                this.attributeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AttributeDataType
        {
            get
            {
                return this.attributeDataTypeField;
            }
            set
            {
                this.attributeDataTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RefAttributeType
        {
            get
            {
                return this.refAttributeTypeField;
            }
            set
            {
                this.refAttributeTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.dke.de/CAEX")]
    public partial class AttributeTypeRefSemantic : CAEXBasicObject
    {

        private string correspondingAttributePathField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CorrespondingAttributePath
        {
            get
            {
                return this.correspondingAttributePathField;
            }
            set
            {
                this.correspondingAttributePathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.dke.de/CAEX")]
    public partial class AttributeValueRequirementType : CAEXBasicObject
    {

        private object itemField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NominalScaledType", typeof(AttributeValueRequirementTypeNominalScaledType))]
        [System.Xml.Serialization.XmlElementAttribute("OrdinalScaledType", typeof(AttributeValueRequirementTypeOrdinalScaledType))]
        [System.Xml.Serialization.XmlElementAttribute("UnknownType", typeof(AttributeValueRequirementTypeUnknownType))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.dke.de/CAEX")]
    public partial class AttributeValueRequirementTypeNominalScaledType
    {

        private string[] requiredValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RequiredValue")]
        public string[] RequiredValue
        {
            get
            {
                return this.requiredValueField;
            }
            set
            {
                this.requiredValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.dke.de/CAEX")]
    public partial class AttributeValueRequirementTypeOrdinalScaledType
    {

        private string requiredMaxValueField;

        private string requiredValueField;

        private string requiredMinValueField;

        /// <remarks/>
        public string RequiredMaxValue
        {
            get
            {
                return this.requiredMaxValueField;
            }
            set
            {
                this.requiredMaxValueField = value;
            }
        }

        /// <remarks/>
        public string RequiredValue
        {
            get
            {
                return this.requiredValueField;
            }
            set
            {
                this.requiredValueField = value;
            }
        }

        /// <remarks/>
        public string RequiredMinValue
        {
            get
            {
                return this.requiredMinValueField;
            }
            set
            {
                this.requiredMinValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.dke.de/CAEX")]
    public partial class AttributeValueRequirementTypeUnknownType
    {

        private string requirementsField;

        /// <remarks/>
        public string Requirements
        {
            get
            {
                return this.requirementsField;
            }
            set
            {
                this.requirementsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.dke.de/CAEX")]
    public partial class AttributeFamilyType : AttributeType
    {

        private AttributeFamilyType[] attributeType1Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttributeType")]
        public AttributeFamilyType[] AttributeType1
        {
            get
            {
                return this.attributeType1Field;
            }
            set
            {
                this.attributeType1Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.dke.de/CAEX")]
    public partial class RoleClassTypeExternalInterface : InterfaceClassType
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InterfaceFamilyType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.dke.de/CAEX")]
    public partial class InterfaceClassType : CAEXObject
    {

        private AttributeType[] attributeField;

        private InterfaceClassType[] externalInterfaceField;

        private string refBaseClassPathField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attribute")]
        public AttributeType[] Attribute
        {
            get
            {
                return this.attributeField;
            }
            set
            {
                this.attributeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExternalInterface")]
        public InterfaceClassType[] ExternalInterface
        {
            get
            {
                return this.externalInterfaceField;
            }
            set
            {
                this.externalInterfaceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RefBaseClassPath
        {
            get
            {
                return this.refBaseClassPathField;
            }
            set
            {
                this.refBaseClassPathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.dke.de/CAEX")]
    public partial class InterfaceFamilyType : InterfaceClassType
    {

        private InterfaceFamilyType[] interfaceClassField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InterfaceClass")]
        public InterfaceFamilyType[] InterfaceClass
        {
            get
            {
                return this.interfaceClassField;
            }
            set
            {
                this.interfaceClassField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.dke.de/CAEX")]
    public partial class RoleFamilyType : RoleClassType
    {

        private RoleFamilyType[] roleClassField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RoleClass")]
        public RoleFamilyType[] RoleClass
        {
            get
            {
                return this.roleClassField;
            }
            set
            {
                this.roleClassField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemUnitFamilyType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InternalElementType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.dke.de/CAEX")]
    public partial class SystemUnitClassType : CAEXObject
    {

        private AttributeType[] attributeField;

        private InterfaceClassType[] externalInterfaceField;

        private InternalElementType[] internalElementField;

        private SystemUnitClassTypeSupportedRoleClass[] supportedRoleClassField;

        private SystemUnitClassTypeInternalLink[] internalLinkField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attribute")]
        public AttributeType[] Attribute
        {
            get
            {
                return this.attributeField;
            }
            set
            {
                this.attributeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExternalInterface")]
        public InterfaceClassType[] ExternalInterface
        {
            get
            {
                return this.externalInterfaceField;
            }
            set
            {
                this.externalInterfaceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InternalElement")]
        public InternalElementType[] InternalElement
        {
            get
            {
                return this.internalElementField;
            }
            set
            {
                this.internalElementField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SupportedRoleClass")]
        public SystemUnitClassTypeSupportedRoleClass[] SupportedRoleClass
        {
            get
            {
                return this.supportedRoleClassField;
            }
            set
            {
                this.supportedRoleClassField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InternalLink")]
        public SystemUnitClassTypeInternalLink[] InternalLink
        {
            get
            {
                return this.internalLinkField;
            }
            set
            {
                this.internalLinkField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.dke.de/CAEX")]
    public partial class InternalElementType : SystemUnitClassType
    {

        private InternalElementTypeRoleRequirements[] roleRequirementsField;

        private string refBaseSystemUnitPathField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RoleRequirements")]
        public InternalElementTypeRoleRequirements[] RoleRequirements
        {
            get
            {
                return this.roleRequirementsField;
            }
            set
            {
                this.roleRequirementsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RefBaseSystemUnitPath
        {
            get
            {
                return this.refBaseSystemUnitPathField;
            }
            set
            {
                this.refBaseSystemUnitPathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.dke.de/CAEX")]
    public partial class InternalElementTypeRoleRequirements : CAEXBasicObject
    {

        private AttributeType[] attributeField;

        private InterfaceClassType[] externalInterfaceField;

        private MappingType mappingObjectField;

        private string refBaseRoleClassPathField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attribute")]
        public AttributeType[] Attribute
        {
            get
            {
                return this.attributeField;
            }
            set
            {
                this.attributeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExternalInterface")]
        public InterfaceClassType[] ExternalInterface
        {
            get
            {
                return this.externalInterfaceField;
            }
            set
            {
                this.externalInterfaceField = value;
            }
        }

        /// <remarks/>
        public MappingType MappingObject
        {
            get
            {
                return this.mappingObjectField;
            }
            set
            {
                this.mappingObjectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RefBaseRoleClassPath
        {
            get
            {
                return this.refBaseRoleClassPathField;
            }
            set
            {
                this.refBaseRoleClassPathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.dke.de/CAEX")]
    public partial class MappingType : CAEXBasicObject
    {

        private MappingTypeAttributeNameMapping[] attributeNameMappingField;

        private MappingTypeInterfaceIDMapping[] interfaceIDMappingField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttributeNameMapping")]
        public MappingTypeAttributeNameMapping[] AttributeNameMapping
        {
            get
            {
                return this.attributeNameMappingField;
            }
            set
            {
                this.attributeNameMappingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InterfaceIDMapping")]
        public MappingTypeInterfaceIDMapping[] InterfaceIDMapping
        {
            get
            {
                return this.interfaceIDMappingField;
            }
            set
            {
                this.interfaceIDMappingField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.dke.de/CAEX")]
    public partial class MappingTypeAttributeNameMapping : CAEXBasicObject
    {

        private string systemUnitAttributeNameField;

        private string roleAttributeNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SystemUnitAttributeName
        {
            get
            {
                return this.systemUnitAttributeNameField;
            }
            set
            {
                this.systemUnitAttributeNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RoleAttributeName
        {
            get
            {
                return this.roleAttributeNameField;
            }
            set
            {
                this.roleAttributeNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.dke.de/CAEX")]
    public partial class MappingTypeInterfaceIDMapping : CAEXBasicObject
    {

        private string systemUnitInterfaceIDField;

        private string roleInterfaceIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SystemUnitInterfaceID
        {
            get
            {
                return this.systemUnitInterfaceIDField;
            }
            set
            {
                this.systemUnitInterfaceIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RoleInterfaceID
        {
            get
            {
                return this.roleInterfaceIDField;
            }
            set
            {
                this.roleInterfaceIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.dke.de/CAEX")]
    public partial class SystemUnitClassTypeSupportedRoleClass : CAEXBasicObject
    {

        private MappingType mappingObjectField;

        private string refRoleClassPathField;

        /// <remarks/>
        public MappingType MappingObject
        {
            get
            {
                return this.mappingObjectField;
            }
            set
            {
                this.mappingObjectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RefRoleClassPath
        {
            get
            {
                return this.refRoleClassPathField;
            }
            set
            {
                this.refRoleClassPathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.dke.de/CAEX")]
    public partial class SystemUnitClassTypeInternalLink : CAEXObject
    {

        private string refPartnerSideAField;

        private string refPartnerSideBField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RefPartnerSideA
        {
            get
            {
                return this.refPartnerSideAField;
            }
            set
            {
                this.refPartnerSideAField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RefPartnerSideB
        {
            get
            {
                return this.refPartnerSideBField;
            }
            set
            {
                this.refPartnerSideBField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.dke.de/CAEX")]
    public partial class SystemUnitFamilyType : SystemUnitClassType
    {

        private SystemUnitFamilyType[] systemUnitClassField;

        private string refBaseClassPathField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SystemUnitClass")]
        public SystemUnitFamilyType[] SystemUnitClass
        {
            get
            {
                return this.systemUnitClassField;
            }
            set
            {
                this.systemUnitClassField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RefBaseClassPath
        {
            get
            {
                return this.refBaseClassPathField;
            }
            set
            {
                this.refBaseClassPathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.dke.de/CAEX")]
    public partial class CAEXFileExternalReference : CAEXBasicObject
    {

        private string pathField;

        private string aliasField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Alias
        {
            get
            {
                return this.aliasField;
            }
            set
            {
                this.aliasField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.dke.de/CAEX")]
    public partial class CAEXFileInstanceHierarchy : CAEXObject
    {

        private InternalElementType[] internalElementField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InternalElement")]
        public InternalElementType[] InternalElement
        {
            get
            {
                return this.internalElementField;
            }
            set
            {
                this.internalElementField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.dke.de/CAEX")]
    public partial class CAEXFileInterfaceClassLib : CAEXObject
    {

        private InterfaceFamilyType[] interfaceClassField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InterfaceClass")]
        public InterfaceFamilyType[] InterfaceClass
        {
            get
            {
                return this.interfaceClassField;
            }
            set
            {
                this.interfaceClassField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.dke.de/CAEX")]
    public partial class CAEXFileRoleClassLib : CAEXObject
    {

        private RoleFamilyType[] roleClassField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RoleClass")]
        public RoleFamilyType[] RoleClass
        {
            get
            {
                return this.roleClassField;
            }
            set
            {
                this.roleClassField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.dke.de/CAEX")]
    public partial class CAEXFileSystemUnitClassLib : CAEXObject
    {

        private SystemUnitFamilyType[] systemUnitClassField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SystemUnitClass")]
        public SystemUnitFamilyType[] SystemUnitClass
        {
            get
            {
                return this.systemUnitClassField;
            }
            set
            {
                this.systemUnitClassField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.dke.de/CAEX")]
    public partial class CAEXFileAttributeTypeLib : CAEXObject
    {

        private AttributeFamilyType[] attributeTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttributeType")]
        public AttributeFamilyType[] AttributeType
        {
            get
            {
                return this.attributeTypeField;
            }
            set
            {
                this.attributeTypeField = value;
            }
        }
    }

    public class Wrapper
    {
        // Default search property
        public CAEXFile CAEXFile { get; set; }

        // First rule
        public SourceDocumentInformationType SourceDocumentInformation { get; set; }

        // Second rule
        public CAEXFileSystemUnitClassLib SystemUnitClassLib { get; set; }

        // Third rule
        public SystemUnitFamilyType SystemUnitClass { get; set; }

        public SystemUnitClassType SystemUnitClassType { get; set; }

        public SystemUnitClassTypeSupportedRoleClass SupportedRoleClass { get; set; }

        public InternalElementType InternalElement { get; set; }

        public AttributeType Attribute { get; set; }

        public InterfaceClassType ExternalInterface { get; set; }

        // Attributes (ID, Name)
        public CAEXObject CAEXObject { get; set; }
    }
}